---
# tasks file for monitoring
- name: Create Node Exporter user
  user:
    name: node_exporter
    shell: /bin/false
    create_home: no
    system: yes

- name: Download and unarchive Node Exporter
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Copy Node Exporter binary
  copy:
    src: /tmp/node_exporter-1.7.0.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    remote_src: yes
    mode: '0755'
    owner: node_exporter
    group: node_exporter

- name: Create Node Exporter service file
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service

- name: Start and enable Node Exporter service
  systemd:
    name: node_exporter
    state: started
    enabled: yes
    daemon_reload: yes