- name: Copy sample PHP app to web root
  copy:
    src: ../../../../sample-php-app/index.php
    dest: /var/www/html/index.php
    owner: www-data
    group: www-data
    mode: '0644'

- name: Copy Apache virtual host config
  template:
    src: 000-default.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  notify: Restart Apache