---
# tasks file for prometheus
- name: Create Prometheus user
  user:
    name: prometheus
    shell: /bin/false
    create_home: no
    system: yes

- name: Create Prometheus directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  with_items:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Download and unarchive Prometheus
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.51.1/prometheus-2.51.1.linux-amd64.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Copy Prometheus binaries
  copy:
    src: "/tmp/prometheus-2.51.1.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    remote_src: yes
    mode: '0755'
    owner: prometheus
    group: prometheus
  with_items:
    - prometheus
    - promtool

- name: Copy Prometheus config files
  copy:
    src: "/tmp/prometheus-2.51.1.linux-amd64/{{ item }}"
    dest: "/etc/prometheus/{{ item }}"
    remote_src: yes
    owner: prometheus
    group: prometheus
  with_items:
    - consoles
    - console_libraries

- name: Create Prometheus configuration
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus

- name: Create Prometheus service file
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service

- name: Start and enable Prometheus service
  systemd:
    name: prometheus
    state: started
    enabled: yes
    daemon_reload: yes